services:
  - type: web
    name: video-downloader-aek
    env: go
    region: frankfurt
    plan: free
    buildCommand: go env -w GO111MODULE=off && go build -o app main.go
    startCommand: ./app
    envVars:
      - key: PORT
        value: 10000
